/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CardRouteImport } from './routes/card'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as MeRouteImport } from './routes/me'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as DealsCategoryRouteImport } from './routes/deals.$category'
import { Route as PayIdRouteImport } from './routes/pay.$id'
import { Route as SCodeRouteImport } from './routes/s.$code'
import { Route as StoreIdRouteImport } from './routes/store.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CardRoute = CardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsCategoryRoute = DealsCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => DealsRoute,
} as any)
const PayIdRoute = PayIdRouteImport.update({
  id: '/pay/$id',
  path: '/pay/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SCodeRoute = SCodeRouteImport.update({
  id: '/s/$code',
  path: '/s/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreIdRoute = StoreIdRouteImport.update({
  id: '/store/$id',
  path: '/store/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/card': typeof CardRoute
  '/deals': typeof DealsRouteWithChildren
  '/me': typeof MeRoute
  '/scan': typeof ScanRoute
  '/deals/$category': typeof DealsCategoryRoute
  '/pay/$id': typeof PayIdRoute
  '/s/$code': typeof SCodeRoute
  '/store/$id': typeof StoreIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/card': typeof CardRoute
  '/deals': typeof DealsRouteWithChildren
  '/me': typeof MeRoute
  '/scan': typeof ScanRoute
  '/deals/$category': typeof DealsCategoryRoute
  '/pay/$id': typeof PayIdRoute
  '/s/$code': typeof SCodeRoute
  '/store/$id': typeof StoreIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/card': typeof CardRoute
  '/deals': typeof DealsRouteWithChildren
  '/me': typeof MeRoute
  '/scan': typeof ScanRoute
  '/deals/$category': typeof DealsCategoryRoute
  '/pay/$id': typeof PayIdRoute
  '/s/$code': typeof SCodeRoute
  '/store/$id': typeof StoreIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/card'
    | '/deals'
    | '/me'
    | '/scan'
    | '/deals/$category'
    | '/pay/$id'
    | '/s/$code'
    | '/store/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/card'
    | '/deals'
    | '/me'
    | '/scan'
    | '/deals/$category'
    | '/pay/$id'
    | '/s/$code'
    | '/store/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/card'
    | '/deals'
    | '/me'
    | '/scan'
    | '/deals/$category'
    | '/pay/$id'
    | '/s/$code'
    | '/store/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CardRoute: typeof CardRoute
  DealsRoute: typeof DealsRouteWithChildren
  MeRoute: typeof MeRoute
  ScanRoute: typeof ScanRoute
  PayIdRoute: typeof PayIdRoute
  SCodeRoute: typeof SCodeRoute
  StoreIdRoute: typeof StoreIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card': {
      id: '/card'
      path: '/card'
      fullPath: '/card'
      preLoaderRoute: typeof CardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals/$category': {
      id: '/deals/$category'
      path: '/$category'
      fullPath: '/deals/$category'
      preLoaderRoute: typeof DealsCategoryRouteImport
      parentRoute: typeof DealsRoute
    }
    '/pay/$id': {
      id: '/pay/$id'
      path: '/pay/$id'
      fullPath: '/pay/$id'
      preLoaderRoute: typeof PayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$code': {
      id: '/s/$code'
      path: '/s/$code'
      fullPath: '/s/$code'
      preLoaderRoute: typeof SCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/$id': {
      id: '/store/$id'
      path: '/store/$id'
      fullPath: '/store/$id'
      preLoaderRoute: typeof StoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DealsRouteChildren {
  DealsCategoryRoute: typeof DealsCategoryRoute
}

const DealsRouteChildren: DealsRouteChildren = {
  DealsCategoryRoute: DealsCategoryRoute,
}

const DealsRouteWithChildren = DealsRoute._addFileChildren(DealsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CardRoute: CardRoute,
  DealsRoute: DealsRouteWithChildren,
  MeRoute: MeRoute,
  ScanRoute: ScanRoute,
  PayIdRoute: PayIdRoute,
  SCodeRoute: SCodeRoute,
  StoreIdRoute: StoreIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
